softwaregroup-bg/ut-run

- debug.js
- test.js
add stop method on implementation level
> feat: add stop method on implementation level

- index.js
- package.json
should be merged with port-httpserver
> Refactoring

- README.md
- test.js
ut-run sequence now returns promise
> BREAKING CHANGE: provide possibility to run subtests and skip steps

- index.js
- test.js
Call ready method after all ports have been started
> Feat/ready - call ready method after all ports have been started

- README.md
- package.json
fix: update dependency to ut-port-registry
> update dependency to ut-port-registry

- index.js
- package.json
Signed-off-by: Krasimir Kostadinov <krasimir.kostadinov@Softwaregroup-bg.com>
> fix: ut-port-registry initialization and updated dependency version

- debug.js
- index.js
> feat: fix cluster mode support

- debug.js
disable console port with runtime arguments
> fix: disable console port with runtime arguments

- index.js
make errors more descriptive by destinguishing missing configuration files from configuration files with errors
> fix: improve error handling

- debug.js
- microservices.md
- package.json
- service.js
BREAKING CHANGE: requires upgrade of ut-port-*
> fix: allow generic creation of ports, modules, erorrs and validations

- package.json
Now port namespace can be defined not only as an array but as a string as well
> feat: update ut-port

- debug.js
- index.js
- package.json
use ut-merge instead uf ut-port/merge
> fix: use ut-merge instead of ut-port/merge

- index.js
fix: global errors are now logged in json format
> fix: format global errors in json format

- package.json
- service/schema.js
get merged config schema from port.configSchema
> feat: get merged config schema from port.configSchema

- Jenkinsfile
- README.md
- bin/ut-doc.js
- browser/doc.js
- browser/unit.js
- doc.js
- methods.js
- package.json
- unit.js
> feat: unit testing wrapper

- .vscode/launch.json
- package.json
- test/index.test.js
- test/unit.test.js
- unit.js
unit test for unit test wrapper
> test: unit test for unit test wrapper

- unit.js
allow passing jobs in unit tests
> test: allow passing jobs in unit tests

- create.js
- package.json
pass implementation version to ut-bus constructor
> feat: pass implementation version to ut-bus constructor

- package.json
- test.js
> fix: polyfill meta in tests

- test.js
pass steps import proxy down the steps chain
> fix: pass steps import proxy down the steps chain

- test.js
> fix: remove performanceTest

- test.js
skip all subsequent tests once a failure occurs
example:
> fix: skip all subsequent tests once a failure occurs

- .vscode/launch.json
- README.md
- bin/ut-doc.js
- bin/ut-run.js
- changelog.js
- package.json
> 'ut-run changelog' initial implementation

- changelog.js
> changelog command fixes #UTCORE-121

- service/install.js
possibility to load a layer in all deployments
> fix: possibility to load a layer in all deployments #UTCORE-121

- changelog.js
handle missing impl-tools server + changelog file reorganization
> fix: handle missing impl-tools server + changelog file reorganization

- .vscode/launch.json
- bin/license.js
- bin/ut-run.js
> fix: ut-run license

- bin/license.js
return encryptionKey, encryptionIV and  encryptionCipher in `license` bin command response
> chore: return encryption parameters in response

- bin/license.js
write parsed license data in stdout and error in stderr
> fix: write parsed license data in stdout #UTCORE-409
